
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author puzzi
 */
public class GuiDB extends javax.swing.JFrame {

    /**
     * Creates new form bd_gui
     */
    public GuiDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Gerar Relatório");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relatorio 1", "Relatorio 2", "Relatorio 3", "Relatorio 4", "Relatorio 5", "Relatorio 6", "Relatorio 7", "Relatorio 8", "Relatorio 9" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    
        reportBD tentativa = new reportBD();      
        String sqlquery = null;
        String escolhaRelat = (String)jComboBox1.getSelectedItem();

        int numero = 13668;
        
        switch (escolhaRelat) {
            case "Relatorio 2":                
                sqlquery =  "SELECT DISTINCT \n" +
                            "EXTRACT(YEAR FROM ven.DATA_VENDA) AS ANO,\n" +
                            "COUNT(ven.CLIENTE_ID) OVER (PARTITION BY EXTRACT(YEAR FROM ven.DATA_VENDA) ORDER BY EXTRACT(YEAR FROM ven.DATA_VENDA)) AS QTD_COMPRA,\n" +
                            "SUM(ven.TOTAL_DEVIDO) OVER (PARTITION BY EXTRACT(YEAR FROM ven.DATA_VENDA) ORDER BY EXTRACT(YEAR FROM ven.DATA_VENDA)) AS SOMA_COMPRA,  \n" +
                            "SUM(ven.TOTAL_DEVIDO) OVER () AS SOMA_TOTAL \n" +
                            "FROM \n" +
                            "VENDA ven INNER JOIN CLIENTE cli ON VEN.CLIENTE_ID = CLI.CLIENTE_ID\n" +
                            "WHERE \n" +
                            "VEN.CLIENTE_ID =" + numero;
                break;            
        
            case "Relatorio 3":
                sqlquery =  "SELECT DISTINCT\n" +
                            "PAIS, \n" +
                            "ESTADO,\n" +
                            "COUNT(ESTADO) OVER (PARTITION BY ESTADO ORDER BY PAIS,ESTADO) as TOTAL_CLIENTE_ESTADO,\n" +
                            "COUNT(PAIS) OVER (PARTITION BY PAIS ORDER BY PAIS) as TOTAL_CLIENTE_PAIS,\n" +
                            "COUNT(PAIS) OVER () as TOTAL_MUNDO\n" +
                            "FROM(\n" +
                            "SELECT DISTINCT \n" +
                            "EST.PAIS     as PAIS,\n" +
                            "EST.NOME     as ESTADO, \n" +
                            "VEN.CLIENTE_ID,\n" +
                            "VEN.VENDA_ID,\n" +
                            "VEN.ENDERECO_ENTREGA \n" +
                            "FROM \n" +
                            "VENDA ven \n" +
                            "INNER JOIN CLIENTE cli ON VEN.CLIENTE_ID = CLI.CLIENTE_ID\n" +
                            "INNER JOIN ENDERECO ende ON VEN.ENDERECO_ENTREGA = ENDE.ENDERECO_ID\n" +
                            "INNER JOIN ESTADO est ON ENDE.ESTADO_ID = EST.ESTADO_ID\n" +
                            "ORDER BY PAIS,ESTADO\n" +
                            ")\n" +
                            "ORDER BY PAIS,ESTADO\n" 
                            ;
                break;
        
            case "Relatorio 4":
                break;
        
        
            case "Relatorio 5":
                break;
             
            case "Relatorio 6":
                break;
        
            case "Relatorio 7":
                break;
        
            case "Relatorio 8":
                break;
                
            case "Relatorio 9":
                break;
        }
            
        
            


        try {         
       
         jTable1.setModel(tentativa.relatorio(sqlquery)); 
            //jTable1.setModel();
        } catch (SQLException ex) {
            Logger.getLogger(GuiDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
