1)

SELECT DISTINCT
  ven.DATA_VENDA,  
  SUM(ven.TOTAL_DEVIDO) OVER (PARTITION BY ven.DATA_VENDA ORDER BY ven.DATA_VENDA) as SOMA,
  AVG(ven.TOTAL_DEVIDO) OVER (ORDER BY ven.DATA_VENDA RANGE BETWEEN INTERVAL '1' DAY PRECEDING AND INTERVAL '1' DAY FOLLOWING) AS MEDIA_CALC
FROM 
  VENDA ven
 	
ORDER BY 1
;

2)

SELECT MES, COUNTER, ROUND(((COUNTER-LAG(COUNTER,1) OVER (ORDER BY MES))*100)/COUNTER,2) AS PROX_MES_PERC 
       
       FROM (
          SELECT DISTINCT
              EXTRACT(MONTH FROM DATA_VENDA) as MES,  
              SUM(ven.TOTAL_DEVIDO) OVER (PARTITION BY EXTRACT(MONTH FROM DATA_VENDA) ORDER BY EXTRACT(MONTH FROM DATA_VENDA)) as COUNTER
          FROM 
                VENDA ven
          WHERE EXTRACT(YEAR FROM ven.DATA_VENDA) = 2012 
          ORDER BY 1
		) 
;



3)

SELECT 
  SUBID, ANO, MES, SOMA_MES, SUM(SOMA_MES) OVER (PARTITION BY SUBID ORDER BY ANO) AS SOMA_ANO
    FROM(
        SELECT 
            sub.SUBCATEGORIA_ID AS SUBID,
            EXTRACT(MONTH FROM ven.DATA_VENDA) AS MES,
            EXTRACT(YEAR FROM ven.DATA_VENDA) AS ANO,
            COUNT(1) AS SOMA_MES
        FROM 
        VENDA ven
            INNER JOIN VENDA_ITEM vi ON ven.VENDA_ID = vi.VENDA_ID
            INNER JOIN PRODUTO pro ON vi.PRODUTO_ID = pro.PRODUTO_ID
            INNER JOIN SUBCATEGORIA sub ON pro.SUBCATEGORIA = sub.SUBCATEGORIA_ID
        GROUP BY sub.SUBCATEGORIA_ID,EXTRACT(YEAR FROM ven.DATA_VENDA),EXTRACT(MONTH FROM ven.DATA_VENDA)
        ORDER BY 1,3
    ) 
    ORDER BY SUBID,ANO,MES
;


SELECT DISTINCT
    sub.SUBCATEGORIA_ID AS SUBID,
    EXTRACT(YEAR FROM ven.DATA_VENDA) AS ANO,
    COUNT(1) OVER (PARTITION BY sub.SUBCATEGORIA_ID ORDER BY EXTRACT(YEAR FROM ven.DATA_VENDA)) as CALC
FROM 
    VENDA ven
    INNER JOIN VENDA_ITEM vi ON ven.VENDA_ID = vi.VENDA_ID
    INNER JOIN PRODUTO pro ON vi.PRODUTO_ID = pro.PRODUTO_ID
    INNER JOIN SUBCATEGORIA sub ON pro.SUBCATEGORIA = sub.SUBCATEGORIA_ID
ORDER BY 1,2
;
