CREATE TABLE "P6513497"."CLIENTE" 
   (	"CLIENTE_ID" NUMBER(38,0), 
	"PESSOA_ID" NUMBER(38,0), 
	"CARTAO_TIPO" VARCHAR2(50 BYTE), 
	"CARTAO_NUMERO" VARCHAR2(25 BYTE), 
	"CARTAO_VALIDADE_MES" NUMBER(38,0), 
	"CARTAO_VALIDADE_ANO" NUMBER(38,0), 
	"NUMERO_CONTA" VARCHAR2(15 BYTE), 
	 CONSTRAINT "CLIENTE_ID_CONSTRAINT" PRIMARY KEY ("CLIENTE_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_CLIENTE_CARTAO_NUMERO" UNIQUE ("CARTAO_NUMERO")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_CLIENTE_NUMERO_CONTA" UNIQUE ("NUMERO_CONTA")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
 	 CONSTRAINT "UK_CLIENTE_PESSOA_ID" UNIQUE ("PESSOA_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "FK_CLIENTE_PESSOA" FOREIGN KEY ("PESSOA_ID")
	 REFERENCES "P6513497"."PESSOA" ("PESSOA_ID") ENABLE
   ) 
  	 SEGMENT CREATION DEFERRED 
         PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016" ;




  CREATE TABLE "P6513497"."DEPARTAMENTO" 
   (	"DEPARTAMENTO_ID" NUMBER(38,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"GRUPO" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_DEPARTAMENTO_ID" PRIMARY KEY ("DEPARTAMENTO_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_DEPARTAMENTO_NOME" UNIQUE ("NOME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE
   ) 
  SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "SCC0541_1SEM_2016";



CREATE TABLE "P6513497"."EMPREGADO" 
   (	"PESSOA_ID" NUMBER(38,0), 
	"DOCUMENTO_NUMERO" VARCHAR2(15 BYTE), 
	"LOGIN_ID" VARCHAR2(256 BYTE), 
	"FUNCAO" VARCHAR2(50 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"ESTADO_CIVIL" CHAR(1 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"DATA_CONTRATATACAO" DATE, 
	"DEPARTAMENTO_ID" NUMBER(38,0), 
	 CONSTRAINT "PK_EMPREGADO_ID" PRIMARY KEY ("PESSOA_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_DOCUMENTO_NUMERO_LOGIN_ID" UNIQUE ("DOCUMENTO_NUMERO", "LOGIN_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_EMPREGADO_ESTADO_CIVIL" CHECK (estado_civil in ('M', 'S')	) ENABLE, 
	 CONSTRAINT "FK_EMPREGADO_DEPARTAMENTO" FOREIGN KEY ("DEPARTAMENTO_ID")
	  REFERENCES "P6513497"."DEPARTAMENTO" ("DEPARTAMENTO_ID") ENABLE, 
	 CONSTRAINT "FK_EMPREGADO_PESSOA" FOREIGN KEY ("PESSOA_ID")
	  REFERENCES "P6513497"."PESSOA" ("PESSOA_ID") ENABLE
   ) 
	SEGMENT CREATION DEFERRED 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	TABLESPACE "SCC0541_1SEM_2016" ;
 


  CREATE TABLE "P6513497"."ENDERECO" 
   (	"ENDERECO_ID" NUMBER(38,0), 
	"ENDERECO_LINHA1" VARCHAR2(60 BYTE), 
	"ENDERECO_LINHA2" VARCHAR2(60 BYTE), 
	"CIDADE" VARCHAR2(30 BYTE), 
	"ESTADO_ID" NUMBER(38,0), 
	"CODIGO_POSTAL" VARCHAR2(15 BYTE), 
	"PESSOA_ID" NUMBER(38,0), 
	 CONSTRAINT "PK_ENDEREDO_ID" PRIMARY KEY ("ENDERECO_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_ENDERECO" UNIQUE ("ENDERECO_LINHA1", "ENDERECO_LINHA2", "CIDADE", "ESTADO_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "FK_ENDERECO_ESTADO" FOREIGN KEY ("ESTADO_ID")
	 REFERENCES "P6513497"."ESTADO" ("ESTADO_ID") ENABLE, 
	 CONSTRAINT "FK_ENDERECO_PESSOA" FOREIGN KEY ("PESSOA_ID")
	 REFERENCES "P6513497"."PESSOA" ("PESSOA_ID") ENABLE
   ) 
	SEGMENT CREATION DEFERRED 
	PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	TABLESPACE "SCC0541_1SEM_2016" ;


 
CREATE TABLE "P6513497"."ESTADO" 
   (	"ESTADO_ID" NUMBER(38,0), 
	"CODIGO_ESTADO" VARCHAR2(3 BYTE), 
	"NOME" VARCHAR2(50 BYTE), 
	"CODIGO_PAIS" VARCHAR2(3 BYTE), 
	"PAIS" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_ESTADO_ID" PRIMARY KEY ("ESTADO_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_CODIGO_ESTADO_CODIGO_PAIS" UNIQUE ("CODIGO_ESTADO", "CODIGO_PAIS")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_ESTADO_NOME" UNIQUE ("NOME")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016" ;
 

CREATE TABLE "P6513497"."IMPOSTO" 
   (	"IMPOSTO_ID" NUMBER(38,0), 
	"ESTADO_ID" NUMBER(38,0), 
	"TIPO" NUMBER(38,0), 
	"TAXA" NUMBER(38,2), 
	"NOME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_IMPOSTO_ID" PRIMARY KEY ("IMPOSTO_ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_ESTADO_ID_TIPO" UNIQUE ("ESTADO_ID", "TIPO")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_IMPOSTO_TIPO" CHECK ((tipo >= 1) AND (tipo <= 3)	) ENABLE, 
	 CONSTRAINT "FK_IMPOSTO_ESTADO" FOREIGN KEY ("ESTADO_ID")
	 REFERENCES "P6513497"."ESTADO" ("ESTADO_ID") ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
         PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016" ;



  CREATE TABLE "P6513497"."METODO_ENTREGA" 
   (	"METODO_ENTREGA_ID" NUMBER(38,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"CARGA_MINIMA" NUMBER(38,2), 
	"CUSTO_LIBRA" NUMBER(38,2), 
	 CONSTRAINT "PK_METODO_ENTREGA_ID" PRIMARY KEY ("METODO_ENTREGA_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_METODO_ENTREGA_NOME" UNIQUE ("NOME")
 	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_METODO_ENTREGA_CARGA_MINIMA" CHECK (carga_minima > 0.00	) ENABLE, 
	 CONSTRAINT "CK_METODO_ENTREGA_CUSTO_LIBRA" CHECK (custo_libra > 0.00	) ENABLE
   ) 		
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;
 


  CREATE TABLE "P6513497"."PESSOA" 
   (	"PESSOA_ID" NUMBER(38,0), 
	"TRATAMENTO" VARCHAR2(8 BYTE), 
	"NOME" VARCHAR2(50 BYTE), 
	"NOME_DO_MEIO" VARCHAR2(50 BYTE), 
	"SOBRENOME" VARCHAR2(50 BYTE), 
	"SUFIXO" VARCHAR2(10 BYTE), 
	"PASSWORD_HASH" VARCHAR2(128 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("PESSOA_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_CLIENTE_EMAIL" UNIQUE ("EMAIL")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
         TABLESPACE "SCC0541_1SEM_2016"  ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;


  CREATE TABLE "P6513497"."PRODUTO" 
   (	"PRODUTO_ID" NUMBER(38,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"NUMERO_PRODUTO" VARCHAR2(25 BYTE), 
	"COR" VARCHAR2(15 BYTE), 
	"PRECO" NUMBER(38,2), 
	"TAMANHO" VARCHAR2(5 BYTE), 
	"UNIDADE_MEDIDA_TAMANHO" CHAR(3 BYTE), 
	"UNIDADE_MEDIDA_PESO" CHAR(3 BYTE), 
	"PESO" NUMBER(8,2), 
	"SUBCATEGORIA" NUMBER(38,0), 
	"FOTO" BLOB, 
	"FOTO_ARQUIVO" VARCHAR2(50 BYTE), 
	"QUANTIDADE" NUMBER(38,0), 
	"MODELO" VARCHAR2(50 BYTE), 
	"DESCRICAO" CLOB, 
	 CONSTRAINT "PK_PRODUTO_ID" PRIMARY KEY ("PRODUTO_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 ONSTRAINT "UK_PRODUCTNUMBER" UNIQUE ("NUMERO_PRODUTO")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_PRODUTO_NOME" UNIQUE ("NOME")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_PRODUTO_PESO" CHECK (peso > 0.00	) ENABLE, 
	 CONSTRAINT "FK_PRODUTO_SUBCATEGORIA" FOREIGN KEY ("SUBCATEGORIA")
	 REFERENCES "P6513497"."SUBCATEGORIA" ("SUBCATEGORIA_ID") ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" 
	 LOB ("FOTO") STORE AS BASICFILE (
	 TABLESPACE "SCC0541_1SEM_2016" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
	 NOCACHE LOGGING ) 
	 LOB ("DESCRICAO") STORE AS BASICFILE (
	 TABLESPACE "SCC0541_1SEM_2016" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
	 NOCACHE LOGGING );

  CREATE TABLE "P6513497"."SUBCATEGORIA" 
   (	"SUBCATEGORIA_ID" NUMBER(38,0), 
	"CATEGORIA" VARCHAR2(11 BYTE), 
	"NOME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_TELEFONE_PESSOA_ID" PRIMARY KEY ("SUBCATEGORIA_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_SUBCATEGORIA_NOME" UNIQUE ("NOME")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_SUBCATEGORIA_CATEGORIA" CHECK (categoria in ('Bicicletas', 'Componentes', 'Roupas', 'Acessórios')	) ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;


  CREATE TABLE "P6513497"."TELEFONE" 
   (	"PESSOA_ID" NUMBER(38,0), 
	"NUMERO" VARCHAR2(25 BYTE), 
	"TIPO" VARCHAR2(8 BYTE), 
	 CONSTRAINT "NUMERO_TIPO" PRIMARY KEY ("NUMERO", "TIPO")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_TELEFONE_TIPO" CHECK (tipo in ('Celular', 'Casa', 'Trabalho')	) ENABLE, 
	 CONSTRAINT "PESSOA_ID_CONSTRAINT" FOREIGN KEY ("PESSOA_ID")
	 REFERENCES "P6513497"."PESSOA" ("PESSOA_ID") ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;




  CREATE TABLE "P6513497"."VENDA" 
   (	"VENDA_ID" NUMBER(38,0), 
	"NUMERO_REVISAO" NUMBER(38,0), 
	"DATA_VENDA" DATE, 
	"DATA_VENCIMENTO" DATE, 
	"DATA_ENVIO" DATE, 
	"STATUS" NUMBER(38,0), 
	"VENDA_NUMERO" VARCHAR2(25 BYTE), 
	"CONTA_NUMERO" VARCHAR2(15 BYTE), 
	"CLIENTE_ID" NUMBER(38,0), 
	"VENDEDOR_ID" NUMBER(38,0), 
	"ENDERECO_COBRANCA" NUMBER(38,0), 
	"ENDERECO_ENTREGA" NUMBER(38,0), 
	"METODO_ENTREGA_ID" NUMBER(38,0), 
	"CODIGO_APROVACAO_CARTAO" VARCHAR2(15 BYTE), 
	"SUBTOTAL" NUMBER(38,2), 
	"IMPOSTOS" NUMBER(38,2), 
	"FRETE" NUMBER(38,2), 
	"TOTAL_DEVIDO" NUMBER(38,2), 
	"COMENTARIO" VARCHAR2(128 BYTE), 
	 CONSTRAINT "VENDA_ID_CONSTRAINT" PRIMARY KEY ("VENDA_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "UK_VENDA_VENDA_NUMERO" UNIQUE ("VENDA_NUMERO")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "VENDA_CLIENTE_CONSTRAINT" FOREIGN KEY ("CLIENTE_ID")
	 REFERENCES "P6513497"."CLIENTE" ("CLIENTE_ID") ENABLE, 
	 CONSTRAINT "FK_VENDA_ENDERECO_COBRANCA" FOREIGN KEY ("ENDERECO_COBRANCA")
	 REFERENCES "P6513497"."ENDERECO" ("ENDERECO_ID") ENABLE, 
	 CONSTRAINT "FK_VENDA_ENDERECO_ENTREGA" FOREIGN KEY ("ENDERECO_ENTREGA")
	 REFERENCES "P6513497"."ENDERECO" ("ENDERECO_ID") ENABLE, 
	 CONSTRAINT "FK_VENDA_METODO_ENTREGA" FOREIGN KEY ("METODO_ENTREGA_ID")
	 REFERENCES "P6513497"."METODO_ENTREGA" ("METODO_ENTREGA_ID") ENABLE, 
	 CONSTRAINT "FK_VENDA_VENDEDOR" FOREIGN KEY ("VENDEDOR_ID")
	 REFERENCES "P6513497"."VENDEDOR" ("PESSOA_ID") ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;




  CREATE TABLE "P6513497"."VENDA_ITEM" 
   (	"VENDA_ID" NUMBER(38,0), 
	"VENDA_ITEM_ID" NUMBER(38,0), 
	"CODIGO_RASTREIO" VARCHAR2(25 BYTE), 
	"QUANTIDADE" NUMBER(38,0), 
	"PRODUTO_ID" NUMBER(38,0), 
	"PRECO_UNITARIO" NUMBER(38,2), 
	"DESCONTO_UNITARIO" NUMBER(38,2), 
	"TOTAL_UNITARIO" NUMBER(38,2), 
	 CONSTRAINT "PK_VENDA_ITEM_VENDA_ID" PRIMARY KEY ("VENDA_ID", "VENDA_ITEM_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_VENDA_ITEM_QUANTIDADE" CHECK (quantidade > 0	) ENABLE, 
	 CONSTRAINT "CK_VENDA_ITEM_PRECO_UNITARIO" CHECK (preco_unitario >= 0.00	) ENABLE, 
	 CONSTRAINT "CK_VENDA_ITEM_DESCONTO" CHECK (desconto_unitario >= 0.00	) ENABLE, 
	 CONSTRAINT "CK_VENDA_ITEM_PRECO" CHECK (preco_unitario >= 0.00	) ENABLE, 
	 CONSTRAINT "FK_VENDA_ITEM_PRODUTO" FOREIGN KEY ("PRODUTO_ID")
	 REFERENCES "P6513497"."PRODUTO" ("PRODUTO_ID") ENABLE, 
	 CONSTRAINT "FK_VENDA_ITEM_VENDA" FOREIGN KEY ("VENDA_ID")
	 REFERENCES "P6513497"."VENDA" ("VENDA_ID") ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;


  CREATE TABLE "P6513497"."VENDEDOR" 
   (	"PESSOA_ID" NUMBER(38,0), 
	"COTA_VENDAS" NUMBER(38,0), 
	"BONUS" NUMBER(38,0), 
	"COMISSAO" NUMBER(38,0), 
	"VENDAS_ANO_ATUAL" NUMBER(38,0), 
	"VENDAS_ULTIMO_ANO" NUMBER(38,0), 
	 CONSTRAINT "PK_VENDEDOR_PESSOA_ID" PRIMARY KEY ("PESSOA_ID")
	 USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016"  ENABLE, 
	 CONSTRAINT "CK_VENDEDOR_BONUS" CHECK (bonus >= 0.00) ENABLE, 
	 CONSTRAINT "CK_VENDEDOR_VENDAS_ULTIMO_ANO" CHECK (vendas_ultimo_ano >= 0.00	) ENABLE, 
	 CONSTRAINT "CK_VENDEDOR_VENDAS_ANO_ATUAL" CHECK (vendas_ano_atual >= 0.00	) ENABLE, 
	 CONSTRAINT "CK_VENDEDOR_COMISSAO" CHECK (comissao >= 0.00	) ENABLE, 
	 CONSTRAINT "CK_VENDEDOR_COTA_VENDAS" CHECK (cota_vendas > 0.00	) ENABLE, 
	 CONSTRAINT "FK_VENDEDOR_EMPREGADO" FOREIGN KEY ("PESSOA_ID")
	 REFERENCES "P6513497"."EMPREGADO" ("PESSOA_ID") ENABLE
   ) 
	 SEGMENT CREATION DEFERRED 
	 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	 TABLESPACE "SCC0541_1SEM_2016" ;
 

 



 
